Add zplug install

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -56,7 +56,36 @@ if [[ "$OS" == "Linux" ]] || [[ "$OS" == "Darwin" ]] ; then
         fi
     done
 
-    echo -e "\nPrezto configuration complete (plugins will be installed on the first shell run)"
+    echo -e "\nPrezto configuration complete"
+
+  # Install zplug
+  if ! command -v zplug > /dev/null; then
+      echo "Installing zplug..."
+      export ZPLUG_HOME="$HOME/.zplug"
+      git clone https://github.com/zplug/zplug $ZPLUG_HOME
+      source $ZPLUG_HOME/init.zsh
+      # If you have zplug commands in your .zshrc, you can run them here to
+      # install your plugins immediately instead of waiting for a new shell
+      # session. For example:
+      # zplug install
+
+      # Select zplug plugins
+      zplug "agkozak/zsh-z"
+      zplug "junegunn/fzf"
+      zplug "yuhonas/zsh-aliases-lsd"
+      zplug "romkatv/powerlevel10k", as:theme, depth:1
+
+      # Make sure that plugins are installed
+      if ! zplug check --verbose; then
+          printf "Installing missing zplug plugins...\n"
+          zplug install
+      fi
+
+  else
+      echo "zplug is already installed."
+  fi
+
+
 else
     echo "This script is only supported on macOS and Linux."
     exit 0
